collections:
  portfolio:

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude: ['node_modules', '/src/', 'webpack.config.js', 'package-lock.json', 'package.json']
permalink: /blog/:title

assetUrl: "https://assets.tommyoldfield.co.uk/"