collections:
  work:
    output: true
    permalink: /:collection/:title

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude: ['node_modules', '/src/', 'webpack.config.js', 'package-lock.json', 'package.json', '*.key', '*.pem']
permalink: /blog/:title

assetUrl: "https://assets.tommyoldfield.co.uk/"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed

whitelist:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
url: https://www.tommyoldfield.co.uk # the base hostname & protocol for your site
domain: tommyoldfield.co.uk
title: Tommy Oldfield
name: Tommy Oldfield
description: Full-Stack Web Developer from Dundee, Scotland
logo: https://assets.tommyoldfield.co.uk/tommy-oldfield-logo-small.png
social:
  name: Tommy Oldfield
  links:
    - https://www.linkedin.com/in/tommyoldfield/
    - https://github.com/oldfieldtc
locale: en_GB
author: Tommy Oldfield