collections:
  portfolio:

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude: ['node_modules']
permalink: /blog/:title

assetUrl: "https://assets.tommyoldfield.co.uk/"