# SEO
url: https://www.tommyoldfield.co.uk # the base hostname & protocol for your site
domain: tommyoldfield.co.uk
title: Tommy Oldfield
name: Tommy Oldfield
description: Full-Stack Web Developer from Dundee, Scotland
logo: https://assets.tommyoldfield.co.uk/tommy-oldfield-logo-small.png
locale: en_GB
author: Tommy Oldfield
