collections:
  work:
    output: true
    permalink: /:collection/:title

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude: ['node_modules', '/src/', 'webpack.config.js', 'package-lock.json', 'package.json', '*.key', '*.pem']
permalink: /blog/:title

assetUrl: "https://assets.tommyoldfield.co.uk/"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

url: "https://www.tommyoldfield.co.uk" # the base hostname & protocol for your site
domain: tommyoldfield.co.uk
