services:
  app:
    container_name: portfolio-dev
    build:
      context: .
      target: runtime  # This tells Docker to stop at the 'development' stage
      args:
        PORT: 5301
    ports:
      - "5301:5301"
    networks:
      - pangolin

networks:
  pangolin:
    external: true
