services:
  astro-app:
    build:
      context: .
      target: runtime
      args:
        PORT: 1234
    container_name: astro-site
    restart: always
    networks:
      - pangolin

networks:
  pangolin:
    external: true
