name: Dev deploy
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: node-24
    steps:
      - name: Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOYER_KEY }}
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd ${{ secrets.DEV_DIRECTORY }} && pwd"
          cd ${{ secrets.DEV_DIRECTORY }}
          git pull origin dev
